# Generated by Django 5.1.15 on 2026-06-17 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(blank=True, help_text='Short identifier shown on reports, e.g. ROC-N.', max_length=12)),
                ('location', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('machine_type', models.CharField(choices=[('linac', 'Linear accelerator'), ('ct_sim', 'CT simulator'), ('brachy', 'Brachytherapy unit'), ('gamma', 'Gamma knife / SRS unit'), ('ortho', 'Orthovoltage / superficial unit'), ('other', 'Other')], default='linac', max_length=16)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='reports.department')),
            ],
            options={
                'ordering': ['department__name', 'name'],
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ReturnToServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outage_start', models.DateTimeField(blank=True, help_text='When the machine went out of service.', null=True)),
                ('work_completed_at', models.DateTimeField(help_text='When repair / maintenance work was completed.')),
                ('work_performed', models.TextField(help_text='Description of the fault and the repair / maintenance performed.')),
                ('performed_by', models.CharField(blank=True, help_text='Engineer or vendor who performed the work.', max_length=160)),
                ('physics_status', models.CharField(choices=[('not_required', 'Not required'), ('performed', 'Performed'), ('pending', 'Required - pending')], default='not_required', max_length=16)),
                ('physics_evaluation', models.TextField(blank=True, help_text='Physics tests / measurements performed before return to service.')),
                ('physicist', models.CharField(blank=True, help_text='Medical physicist who performed / oversaw the evaluation.', max_length=160)),
                ('approved_by', models.CharField(blank=True, help_text='Name and role of the person approving return to service.', max_length=160)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('vendor_doc_url', models.URLField(blank=True, help_text="Link to the vendor's service report / documentation of the repair.", verbose_name='Vendor documentation link')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('returned', 'Returned to service')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rts_reports', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rts_reports', to='reports.machine')),
            ],
            options={
                'verbose_name': 'return-to-service report',
                'ordering': ['-work_completed_at', '-created_at'],
            },
        ),
    ]
