# Generated by Django 5.1.15 on 2026-06-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returntoservicereport',
            name='vendor_doc_url',
            field=models.CharField(blank=True, help_text="Link to the vendor's service report / documentation of the repair.", max_length=160, verbose_name='Vendor documentation link'),
        ),
    ]
